import type { EngineModuleDefinition } from '../../core/module-types.js'

export const REVOPS_MODULES = [
  { id: 'deal-routing', name: 'Deal Routing', description: 'Route qualified replies and synchronize CRM outcomes.', status: 'available', sourcePaths: ['workflows/pre-crm/reply-to-deal.workflow.json', 'core/revops/contracts/routing-contract.ts'], workflowIds: ['pre-crm.reply-to-deal'] },
  { id: 'customer-lifecycle', name: 'Customer Lifecycle', description: 'Represent reusable lifecycle and retention states.', status: 'extracted', sourcePaths: ['core/revops/contracts/retention-contract.ts'], workflowIds: [] },
  { id: 'retention', name: 'Retention', description: 'Evaluate reusable retention and intervention contracts.', status: 'extracted', sourcePaths: ['core/revops/contracts/retention-contract.ts'], workflowIds: [] },
  { id: 'revenue-signals', name: 'Revenue Signals', description: 'Generate and process persisted revenue-operation signals.', status: 'available', sourcePaths: ['workflows/revops/signal-orchestration.workflow.json', 'core/pre-crm/n8n-code-nodes/n8n-revops-signal-split.js'], workflowIds: ['revops.signal-orchestration'] },
  { id: 'activation', name: 'Activation', description: 'Consume existing account activation and subscription activation signals.', status: 'available', sourcePaths: ['core/revops/contracts/database-signals.ts', 'runtime/signal-engine.ts'], workflowIds: ['revops.signal-orchestration'] },
  { id: 'adoption', name: 'Adoption', description: 'Use existing product-event, provider, budget, and usage capabilities without introducing new thresholds.', status: 'available', sourcePaths: ['core/revops/contracts/database-signals.ts', 'core/product-signals.ts'], workflowIds: ['revops.signal-orchestration'] },
  { id: 'health-score', name: 'Health Score', description: 'Reuse evaluate_account_health and current_customer_health as the authoritative health model.', status: 'available', sourcePaths: ['core/revops/contracts/retention-contract.ts', 'core/revops/contracts/database-signals.ts'], workflowIds: ['revops.signal-orchestration'] },
  { id: 'expansion', name: 'Expansion', description: 'Normalize existing expansion candidate, usage growth, and upgrade intent signals.', status: 'available', sourcePaths: ['core/revops/contracts/database-signals.ts'], workflowIds: ['revops.signal-orchestration'] },
  { id: 'risk-signals', name: 'Risk Signals', description: 'Normalize existing account risk, churn, budget, allowance, and inactivity signals.', status: 'available', sourcePaths: ['core/revops/contracts/database-signals.ts'], workflowIds: ['revops.signal-orchestration'] },
  { id: 'usage-intelligence', name: 'Usage Intelligence', description: 'Represent existing provider usage and significant-growth signals.', status: 'available', sourcePaths: ['core/revops/contracts/database-signals.ts'], workflowIds: ['revops.signal-orchestration'] },
  { id: 'power-user', name: 'Power User', description: 'Detect sustained expert activity from persisted product events.', status: 'available', sourcePaths: ['core/product-signals.ts', 'runtime/signal-engine.ts'], workflowIds: [] },
  { id: 'customer-success', name: 'Customer Success', description: 'Expose existing intervention, owner, and project-sharing signals for downstream action.', status: 'available', sourcePaths: ['core/product-signals.ts', 'core/revops/contracts/database-signals.ts'], workflowIds: ['revops.signal-orchestration'] },
] as const satisfies readonly EngineModuleDefinition[]
