import type { FieldDefinition, TriggerDefinition } from '../core/types.js'

const eventOutput: FieldDefinition = {
  name: 'event',
  type: 'object',
  required: true,
  description: 'Normalized event payload emitted by the trigger.',
}

export const TRIGGER_DEFINITIONS = [
  {
    id: 'webhook',
    name: 'Webhook',
    description: 'Accept an authenticated inbound HTTP event.',
    configuration: [
      { name: 'path', type: 'string', required: true, description: 'Unique webhook path.' },
      { name: 'method', type: 'string', required: true, description: 'Accepted HTTP method.' },
    ],
    inputs: [{ name: 'request', type: 'object', required: true, description: 'Inbound HTTP request.' }],
    outputs: [eventOutput],
    validation: ['path must be unique', 'method must be allowlisted', 'payload size must be bounded'],
    supportedWorkflows: ['pre-crm.lead-qualification'],
  },
  {
    id: 'cron',
    name: 'Cron',
    description: 'Start a workflow from a deterministic schedule.',
    configuration: [{ name: 'schedule', type: 'string', required: true, description: 'Cron or interval expression.' }],
    inputs: [],
    outputs: [eventOutput],
    validation: ['schedule must parse', 'minimum interval must respect runtime limits'],
    supportedWorkflows: ['pre-crm.reply-to-deal', 'revops.signal-orchestration'],
  },
  {
    id: 'email',
    name: 'Email',
    description: 'Start from a normalized inbound email event.',
    configuration: [{ name: 'mailbox', type: 'string', required: true, description: 'Connected mailbox identifier.' }],
    inputs: [{ name: 'message', type: 'object', required: true, description: 'Provider email payload.' }],
    outputs: [eventOutput],
    validation: ['mailbox connection must exist', 'message identifier must be idempotent'],
    supportedWorkflows: [],
  },
  {
    id: 'slack-event',
    name: 'Slack',
    description: 'Start from a verified Slack event callback.',
    configuration: [{ name: 'eventTypes', type: 'array', required: true, description: 'Allowed Slack event types.' }],
    inputs: [{ name: 'callback', type: 'object', required: true, description: 'Verified Slack callback.' }],
    outputs: [eventOutput],
    validation: ['signature must be verified', 'retry identifiers must be deduplicated'],
    supportedWorkflows: [],
  },
  {
    id: 'hubspot-event',
    name: 'HubSpot',
    description: 'Start from a HubSpot subscription event.',
    configuration: [{ name: 'subscriptionTypes', type: 'array', required: true, description: 'Allowed subscription types.' }],
    inputs: [{ name: 'events', type: 'array', required: true, description: 'HubSpot event batch.' }],
    outputs: [eventOutput],
    validation: ['signature must be verified', 'event IDs must be deduplicated'],
    supportedWorkflows: [],
  },
  {
    id: 'supabase-change',
    name: 'Supabase',
    description: 'Start from a database change event emitted by Supabase.',
    configuration: [{ name: 'table', type: 'string', required: true, description: 'Allowlisted source table.' }],
    inputs: [{ name: 'change', type: 'object', required: true, description: 'Database change payload.' }],
    outputs: [eventOutput],
    validation: ['table must be allowlisted', 'event must include a stable record identifier'],
    supportedWorkflows: [],
  },
  {
    id: 'http',
    name: 'HTTP',
    description: 'Start from a normalized HTTP request handled by an embedding service.',
    configuration: [{ name: 'route', type: 'string', required: true, description: 'Registered backend route.' }],
    inputs: [{ name: 'request', type: 'object', required: true, description: 'Authenticated request context.' }],
    outputs: [eventOutput],
    validation: ['route must be registered', 'caller must be authorized'],
    supportedWorkflows: [],
  },
  {
    id: 'database-change',
    name: 'Database',
    description: 'Start from a provider-neutral database mutation event.',
    configuration: [{ name: 'source', type: 'string', required: true, description: 'Registered database source.' }],
    inputs: [{ name: 'change', type: 'object', required: true, description: 'Normalized mutation.' }],
    outputs: [eventOutput],
    validation: ['source must be registered', 'mutation must be idempotent'],
    supportedWorkflows: [],
  },
  {
    id: 'internal-event',
    name: 'Internal Event',
    description: 'Start from a trusted backend lifecycle event.',
    configuration: [{ name: 'eventNames', type: 'array', required: true, description: 'Allowed internal event names.' }],
    inputs: [{ name: 'event', type: 'object', required: true, description: 'Trusted lifecycle event.' }],
    outputs: [eventOutput],
    validation: ['event name must be registered', 'workspace scope must be present'],
    supportedWorkflows: ['revops.signal-orchestration'],
  },
  {
    id: 'ai-event',
    name: 'AI Event',
    description: 'Start from a persisted AI generation lifecycle event.',
    configuration: [{ name: 'eventNames', type: 'array', required: true, description: 'Allowed generation event names.' }],
    inputs: [{ name: 'generation', type: 'object', required: true, description: 'Persisted generation event.' }],
    outputs: [eventOutput],
    validation: ['generation ID must exist', 'project and workspace scope must match'],
    supportedWorkflows: [],
  },
] as const satisfies readonly TriggerDefinition[]
